# Generated by Django 4.2.3 on 2023-08-21 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_expense_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='expense',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
